### ISSUE TITLE
新しい漫画RSS要求

### ISSUE THREAD

**Issue by storyofwind** [background-color/webcomic-crawler#8]
こんにちは、
初めてGitHubを利用し、もしここに要求することは不適切なら、お許し下さい。
くらげバンチの「山と食欲と私」と「宇宙戦艦ティラミス」のRSSを作っていただけませんか。
ありがとうございます。

**Comment by background-color** [comment]
くらげバンチの「山と食欲と私」と「宇宙戦艦ティラミス」追加しました
